apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

patchesStrategicMerge:
  - patch-ingress-host.yaml
  - patch-configmaps.yaml

resources:
  - ../../base
  - managedcertificate.yaml
