apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigw
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: apigw-cert
spec:
  rules:
    - host: api.omgtv.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigw
                port:
                  number: 3000
