apiVersion: v1
kind: ConfigMap
metadata:
  name: apigw-config
data:
  REDIS_URL: "redis://10.117.209.35:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: content-service-config
data:
  CDN_BASE_URL: "https://cdn.dev.pocketlol.example"
  REDIS_URL: "redis://10.117.209.35:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: engagement-service-config
data:
  REDIS_URL: "redis://10.117.209.35:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  FIREBASE_PROJECT_ID: "pocketlol-68ca6"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-service-config
data:
  REDIS_URL: "redis://10.117.209.35:6379"
  GCP_PROJECT_ID: "pocketlol-68ca6"
  PUBSUB_PROJECT_ID: "pocketlol-68ca6"
  UPLOAD_BUCKET: "videos-bucket-pocketlol"
  CDN_UPLOAD_BASE_URL: "https://upload.cdn.pocketlol"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-service-config
data:
  REDIS_URL: "redis://10.117.209.35:6379"
  RAZORPAY_KEY_ID: "rzp_test_RBSer2L2HUkTuM"
  RAZORPAY_KEY_SECRET: "qqc0A1nLgTEBYghAQwQJr9IZ"
  RAZORPAY_WEBHOOK_SECRET: "whsec_omgtv_68"
  AUTH_SERVICE_ADDRESS: "auth-service:50051"
  USER_SERVICE_ADDRESS: "user-service:50052"
