apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigw
  annotations:
    networking.gke.io/managed-certificates: dev-apigw-cert
spec:
  rules:
    - host: dev.api.omgtv.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigw
                port:
                  number: 3000
